### ISSUE TITLE
oslo-policy in tripleo openstack

### ISSUE THREAD

**Issue by rpathak143** [JAORMX/JAORMX.github.io#8]
Hi,

I have read your blogs regarding oslo-policy in openstack. Really nice, but as unfortunately I am not able to apply them. My requirement is to set oslo-policy for read-only user who can view the things but don't touch anything. Also would like to give access to manage only security group to that role. How can i achieve this? 
what is the best way to create implied role and use them in our tripleo openstack policies for a viewer user only and just able to make changes in security group only.

Awaiting your positive feedback on my requirement.

**Comment by JAORMX** [comment]
@rpathak143 right, at the time of writing it was non-trivial to create custom roles in OpenStack. That's why I started researching using Open Policy Agent to do a centralized policy. That work didn't get enough traction, so it stalled.

SOME services have a parameter to set custom policies. And you would set the file like this: http://tripleo.org/install/advanced_deployment/api_policies.html?highlight=configuring%20api%20access%20policies

But you really need to know how to create policies, else you can get nasty issues in your deployment.

If you have support from a vendor, you should really reach out to them.

**Comment by rpathak143** [comment]
Thanks for your reply. 

Actually, there is reader member in default setup of tripleo. But when i create any project with this member, this user can do anything like a member but it should be read only user. So I was thinking there must be some custom policies need to be created for this task.

I have another concern about tripleo, I am sure you can help me. I have read RECOMMENDATIONS FOR LARGE DEPLOYMENTS for overcloud and did my setup accordingly . But once I create 70 to 75 instances and same number of network in 70 projects, controller high availability disturbed and cluster spoiled totally. 

Is there any specific setting we need to do while overcloud deployment, I mean configuration changes in software or files to achieve atleast 2000 vms in 500 projects.

Your help in this will be life saver for me.

Thanks in advance.

**Comment by JAORMX** [comment]
@rpathak143 I recommend you reach out to the TripleO team in freenode in #tripleo. The team is quite responsive and I'm sure they'll be able to help. Unfortunately it's been a while since I've been doing TripleO, and am now working on OpenShift/Kubernetes. So, my knowledge might be a little out of date.
